# Generated by Django 4.0.4 on 2022-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_participante_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='part',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
