# Generated by Django 4.0.4 on 2022-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_participante_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='chave',
            field=models.CharField(default='77d65', max_length=5),
        ),
    ]
