# Generated by Django 4.0.6 on 2022-07-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='crypt_key',
        ),
    ]
