# Generated by Django 4.0.6 on 2022-07-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classe_room_host_message_room_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
