# Generated by Django 4.0.6 on 2022-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
