# Generated by Django 4.0.4 on 2022-07-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_message_created_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='crypt_key',
            field=models.TextField(default='capsulat', max_length=23),
            preserve_default=False,
        ),
    ]
