# Generated by Django 4.0.6 on 2022-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_crypt_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='crypt_key',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
