# Generated by Django 4.0.6 on 2022-07-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_crypt_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_in',
            field=models.TextField(blank=True, default='capsulat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='crypt_key',
            field=models.CharField(default='capsulat', max_length=23),
            preserve_default=False,
        ),
    ]
