# Generated by Django 4.0.6 on 2022-07-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_room_room_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='data_control',
            field=models.DateField(default='2022-12-25'),
        ),
    ]
