# Generated by Django 4.0.6 on 2022-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_room_data_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='data_control',
        ),
        migrations.AddField(
            model_name='room',
            name='date_control',
            field=models.DateField(auto_now=True),
        ),
    ]
