# Generated by Django 4.0.6 on 2022-07-30 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_room_data_control_room_date_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_control',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
