# Generated by Django 4.0.6 on 2022-07-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_room_date_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_control_initial',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
