# Generated by Django 4.0.6 on 2022-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_room_date_control_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_control_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
