# Generated by Django 4.0.6 on 2022-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_room_date_control_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_in',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='crypt_key',
            field=models.CharField(default='capsulat', max_length=23),
        ),
    ]
